#!/bin/bash -e
# Copyright (C) 2016 Endless Mobile, Inc.
# Licensed under the GPLv2

USERID=$(id -u)
if [ "$USERID" != "0" ]; then
    echo "Program requires superuser privileges"
    exit 1
fi

DEB_ARCH=`dpkg --print-architecture`
case ${DEB_ARCH} in
    amd64) ;; # Only 64-bit Intel architectures are supported
    *) echo "Unsupported architecture ${DEB_ARCH}"
       exit 1
       ;;
esac

TEMP_DIR=`mktemp -d`
DEST_DIR=/var/lib/chromium-plugins-extra/eos-chrome-plugin-updater
WGET_COMMAND="wget -c --tries=5"
DAYS_CHECK=7

# Data needed for the Flash plugin, from Adobe
FLASH_FALLBACK_VERSION="23.0.0.185"
FLASH_FALLBACK_URL="https://fpdownload.adobe.com/pub/flashplayer/pdc/${FLASH_FALLBACK_VERSION}/flash_player_ppapi_linux.$(arch).tar.gz"
FLASH_FALLBACK_SHA256SUM="3f7a13a615d3cf19e5feb02485e12e3785a6ef07cd7ae32072cd860468fd322b"

FLASH_LKGV_FILE_URL="https://s3-us-west-2.amazonaws.com/abacadaba/flashplugin-$(arch).lkgv"
FLASH_LKGV_VERSION=
FLASH_LKGV_URL=
FLASH_LKGV_SHA256SUM=
FLASH_LKGV_FILENAME=

FLASH_VERSION=
FLASH_SO_FILE=libpepflashplayer.so
FLASH_VERSION_FILE=${DEST_DIR}/Flash_VERSION.txt

# Data needed for the Widevine plugin, from Google Chrome
CHROME_URL=http://dl.google.com/linux/chrome/deb
CHROME_PACKAGES=${CHROME_URL}/dists/stable/main/binary-${DEB_ARCH}/Packages
CHROME_FLAVOUR_VERSION=google-chrome-stable
CHROME_VERSION=
CHROME_SHA1SUM=
CHROME_URL_FILENAME=
CHROME_FILENAME=

WIDEVINE_VERSION=
WIDEVINE_SO_FILE=/opt/google/chrome/libwidevinecdm.so
WIDEVINE_VERSION_FILE=${DEST_DIR}/Widevine_VERSION.txt
WIDEVINE_OLD_VERSION_FILE=${DEST_DIR}/VERSION.txt

fp_init() {
    mkdir -p ${DEST_DIR}
}

fp_exit() {
   echo $1
   rm -fr ${TEMP_DIR}
   exit 0
}

fp_get_field() {
    grep-dctrl -n -s $1 ${CHROME_FLAVOUR_VERSION} ${TEMP_DIR}/Packages
}

fp_refresh_version_file() {
    local version_file="$1"
    if [ ! -f ${version_file} ]; then
        echo "Version file ${version_file} does not exist. Nothing to refresh"
        return
    fi

    if [ ! -s ${version_file} ]; then
        echo "Version file ${version_file} is invalid (empty). Removing..."
        rm -f ${version_file}
        return;
    fi

    echo "Refreshing version file ${version_file}..."
    touch ${version_file}
}

fp_should_check_updates_flash() {
    local should_check_updates=true
    if [ ! -f ${FLASH_VERSION_FILE} ] ; then
        FLASH_VERSION="not installed"
    else
        FLASH_VERSION=$(cat ${FLASH_VERSION_FILE})
        if [ -z "${FLASH_VERSION}" ]; then
            rm -f ${FLASH_VERSION_FILE}
        elif ! [ `find ${FLASH_VERSION_FILE} -daystart -mtime +${DAYS_CHECK}` ] && \
             ! [ `find ${FLASH_VERSION_FILE} -newermt "0 days"` ] ; then
            # Has been checked recently. No need to check
            should_check_updates=false
        fi
    fi

    if ! ${should_check_updates}; then
        echo "No need to check the Flash plugin yet (version: ${FLASH_VERSION})"
        return 1;
    fi

    echo "Flash plugin is not installed or might be too old. Checking for a new version"
    return 0
}

fp_should_check_updates_widevine() {
    local should_check_updates=true

    # Migrate the old VERSION.txt file if present AND is not empty
    if [ -s ${WIDEVINE_OLD_VERSION_FILE} ]; then
        mv ${WIDEVINE_OLD_VERSION_FILE} ${WIDEVINE_VERSION_FILE}
    else
        # Make sure an empty file gets removed
        rm -f ${WIDEVINE_OLD_VERSION_FILE}
    fi

    if [ ! -f ${WIDEVINE_VERSION_FILE} ] ; then
        WIDEVINE_VERSION="not installed"
    else
        WIDEVINE_VERSION=$(cat ${WIDEVINE_VERSION_FILE})
        if [ -z "${WIDEVINE_VERSION}" ]; then
            rm -f ${WIDEVINE_VERSION_FILE}
        elif ! [ `find ${WIDEVINE_VERSION_FILE} -daystart -mtime +${DAYS_CHECK}` ] && \
             ! [ `find ${WIDEVINE_VERSION_FILE} -newermt "0 days"` ] ; then
            # Has been checked recently. No need to check
            should_check_updates=false
        fi
    fi

    if ! ${should_check_updates}; then
        echo "No need to check the Widevine plugin yet (version: ${WIDEVINE_VERSION})"
        return 1;
    fi

    echo "Widevine plugin is not installed or might be too old. Checking for a new version"
    return 0
}

fp_fetch_flash_metadata() {
    local filename=$(basename ${FLASH_LKGV_FILE_URL})
    if ${WGET_COMMAND} "${FLASH_LKGV_FILE_URL}" -O "${TEMP_DIR}/${filename}"; then
        while IFS='=' read key value; do
            case "$key" in
                "VERSION") FLASH_LKGV_VERSION="$value" ;;
                "URL") FLASH_LKGV_URL="$value" ;;
                "SHA256SUM") FLASH_LKGV_SHA256SUM="$value" ;;
                *) ;;
            esac
        done < ${TEMP_DIR}/${filename}
    else
        echo "Failed to retrieve the last known good version of the flash plugin"
        echo "Using fallbacks values (Flash plugin version: ${FLASH_FALLBACK_VERSION})"

        FLASH_LKGV_VERSION="${FLASH_FALLBACK_VERSION}"
        FLASH_LKGV_SHA256SUM="${FLASH_FALLBACK_SHA256SUM}"
        FLASH_LKGV_URL="${FLASH_FALLBACK_URL}"
    fi

    # This will be needed then downloading and installing
    FLASH_LKGV_FILENAME=$(basename ${FLASH_LKGV_URL})
}

fp_fetch_widevine_metadata() {
    if ! ${WGET_COMMAND} "${CHROME_PACKAGES}" -O "${TEMP_DIR}/Packages"; then
        echo "Failed to download Packages from Google Chrome"
        return 1
    fi

    local package=$(fp_get_field "Package")
    if [ -z "${package}" ]; then
        echo "Packages does not contain ${CHROME_FLAVOUR_VERSION}"
        return 1
    fi

    CHROME_VERSION=$(fp_get_field "Version")
    CHROME_SHA1SUM=$(fp_get_field "SHA1")

    local filename=$(fp_get_field "Filename")
    CHROME_URL_FILENAME=${CHROME_URL}/${filename}
    CHROME_FILENAME=${CHROME_URL_FILENAME##*/}
}

fp_should_update_flash() {
    if fp_fetch_flash_metadata; then
       if [ "${FLASH_VERSION}" = "${FLASH_LKGV_VERSION}" ] ; then
           # Refresh the VERSION so it is not checked again until ${DAYS_CHECK} passed
           echo "Flash plugin is up-to-date"
           fp_refresh_version_file ${FLASH_VERSION_FILE}
           return 1
       else
           echo "A new version of the flash plugin is available: ${FLASH_LKGV_VERSION}"
           return 0
       fi
    else
        echo "An error happened fetching metadata for the the Flash plugin"
        return 1
    fi
}

fp_should_update_widevine() {
    if fp_fetch_widevine_metadata; then
       if [ "${WIDEVINE_VERSION}" = "${CHROME_VERSION}" ] ; then
           # Refresh the VERSION so it is not checked again until ${DAYS_CHECK} passed
           echo "Widevine plugin is up-to-date"
           fp_refresh_version_file ${WIDEVINE_VERSION_FILE}
           return 1
       else
           echo "A new version of the widevine plugin is available: ${CHROME_VERSION}"
           return 0
       fi
    else
        echo "An error happened fetching metadata for the Widevine plugin"
        return 1
    fi
}

fp_download_google_chrome() {
    # Get Chrome
    echo "Downloading ${CHROME_FILENAME}"
    if ! ${WGET_COMMAND} "${CHROME_URL_FILENAME}" -O "${TEMP_DIR}/${CHROME_FILENAME}"; then
        echo "Failed to download ${CHROME_FILENAME}"
        return 1
    fi

    # Verify SHA1 checksum of debian file
    echo "Verifying ${TEMP_DIR}/${CHROME_FILENAME}"
    echo "${CHROME_SHA1SUM} ${TEMP_DIR}/${CHROME_FILENAME}" | sha1sum -c > /dev/null 2>&1 || \
    {
        echo "sha1sum mismatch ${TEMP_DIR}/${CHROME_FILENAME}"
        return 1
    }
}

fp_download_adobe_flash() {
    # Get the Adobe Flash Plugin
    echo "Downloading ${FLASH_LKGV_FILENAME}"
    if ! ${WGET_COMMAND} "${FLASH_LKGV_URL}" -O "${TEMP_DIR}/${FLASH_LKGV_FILENAME}"; then
        echo "Failed to download ${FLASH_LKGV_URL}"
        return 1
    fi

    # Verify SHA256 checksum of debian file
    echo "Verifying ${TEMP_DIR}/${FLASH_LKGV_FILENAME}"
    echo "${FLASH_LKGV_SHA256SUM} ${TEMP_DIR}/${FLASH_LKGV_FILENAME}" | sha256sum -c > /dev/null 2>&1 || \
    {
        echo "sha256sum mismatch ${TEMP_DIR}/${FLASH_LKGV_FILENAME}"
        return 1
    }
}

fp_install_flash_plugin() {
    echo "Installing ${TEMP_DIR}/${FLASH_LKGV_FILENAME}"
    if ! tar zxv -C ${TEMP_DIR} -f ${TEMP_DIR}/${FLASH_LKGV_FILENAME} ; then
        echo "Cannot extract files from ${FLASH_LKGV_FILENAME}"
    elif ! [ -f ${TEMP_DIR}/${FLASH_SO_FILE} ]; then
        echo "Could not find ${FLASH_SO_FILE}"
    elif ! install -m 644 ${TEMP_DIR}/${FLASH_SO_FILE} ${DEST_DIR} ; then
        echo "Could not copy ${FLASH_SO_FILE} into ${DEST_DIR}"
    else
        # Sanity check: don't ever write a VERSION file with an empty value
        if [ -n "${FLASH_LKGV_VERSION}" ]; then
            echo -n "${FLASH_LKGV_VERSION}" > ${FLASH_VERSION_FILE}
        fi
        echo "Flash plugin installed"
        return
    fi

    echo "Flash plugin could NOT be installed"
}

fp_install_widevine_plugin() {
    echo "Installing ${TEMP_DIR}/${CHROME_FILENAME}"
    if ! dpkg -x ${TEMP_DIR}/${CHROME_FILENAME} ${TEMP_DIR}/unpackedchrome ; then
        echo "Cannot unpack package file ${CHROME_FILENAME}"
    elif ! [ -f ${TEMP_DIR}/unpackedchrome${WIDEVINE_SO_FILE} ]; then
        echo "Could not find ${WIDEVINE_SO_FILE}"
    elif ! install -m 644 ${TEMP_DIR}/unpackedchrome${WIDEVINE_SO_FILE} ${DEST_DIR} ; then
        echo "Could not copy ${WIDEVINE_SO_FILE} into ${DEST_DIR}"
    else
        # Sanity check: don't ever write a VERSION file with an empty value
        if [ -n "${CHROME_VERSION}" ]; then
            echo -n "${CHROME_VERSION}" > ${WIDEVINE_VERSION_FILE}
        fi
        echo "Widevine plugin installed"
        return
    fi

    echo "Widevine plugin could NOT be installed"
}

fp_init

# Flash plugin
if fp_should_check_updates_flash ; then
    if fp_should_update_flash && fp_download_adobe_flash; then
        fp_install_flash_plugin
    else
        echo "The Flash plugin was NOT updated"
    fi
fi

# Widevine plugin
if fp_should_check_updates_widevine ; then
    if fp_should_update_widevine && fp_download_google_chrome; then
        fp_install_widevine_plugin
    else
        echo "The Widevine plugin was NOT updated"
    fi
fi

fp_exit "All done"

# vim: ts=2 sw=2
